apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespaces
  - namespace.yaml

  # kube-soomkiller
  - serviceaccount.yaml
  - rbac.yaml
  - daemonset.yaml

  # Test workloads (MariaDB + Sysbench)
  - mariadb-statefulset.yaml
  - mariadb-service.yaml
  - sysbench-deployment.yaml

  # Monitoring
  - node-exporter-daemonset.yaml
  - prometheus-configmap.yaml
  - prometheus-statefulset.yaml
